- name: Provision overcloud
  hosts: localhost
  tasks:
    - openstack.cloud.baremetal_node_action:
        name: "test-vm"
        config_drive:
          meta_data:
            hostname: node1
          network_data:
            links:
              - id: port-
                type: phy
                ethernet_mac_address:
            networks:
              - id: network0
                type: ipv4
                link: port-
                ip_address: "192.168.124.42"
                netmask: "255.255.255.0"
                network_id: network0
        instance_info:
          image_source: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
          image_checksum: "071fceadf1ea57a388ff7a1ccb4127155d691a511f6a207b4c11b120563855e2"
          image_disk_format: "qcow2"
