SUSHY_EMULATOR_STORAGE = {
    "f84aa5b8-b1ef-4478-81e8-0fe530a7fdde": [
        {
            "Id": "1",
            "Name": "Local Storage Controller",
            "StorageControllers": [
                {
                    "MemberId": "0",
                    "Name": "Contoso Integrated RAID",
                    "SpeedGbps": 12
                }
            ],
            "Drives": [
                "32ADF365C6C1B7BD"
            ]
        }
    ]
}

SUSHY_EMULATOR_DRIVES = {
    ("f84aa5b8-b1ef-4478-81e8-0fe530a7fdde", "1"): [
        {
            "Id": "32ADF365C6C1B7BD",
            "Name": "Drive Sample",
            "CapacityBytes": 899527000000,
            "Protocol": "SAS"
        }
    ]
}

SUSHY_EMULATOR_VOLUMES = {
    ('f84aa5b8-b1ef-4478-81e8-0fe530a7fdde', '1'): [
        {
            "libvirtPoolName": "default",
            "libvirtVolName": "vbmc-node-test3.qcow2",
            "Id": "1",
            "Name": "vbmc-node-volume",
            "VolumeType": "File",
            "CapacityBytes": 1073741824
        }
    ]
}
