[DEFAULT]
enabled_hardware_types = redfish
enabled_boot_interfaces = redfish-virtual-media,redfish-https
enabled_power_interfaces = redfish
enabled_management_interfaces = redfish
enabled_inspect_interfaces = agent,redfish
default_network_interface = noop
default_boot_interface = redfish-virtual-media

[conductor]
deploy_kernel = http://192.168.33.3:8089/ironic-agent.kernel
deploy_ramdisk =  http://192.168.33.3:8089/ironic-agent.initramfs
bootloader = file:///var/lib/ironic/httpboot/esp.img

[neutron]
cleaning_network = none
