[DEFAULT]
enabled_hardware_types = redfish
enabled_boot_interfaces = ipxe,redfish-virtual-media,redfish-https
enabled_power_interfaces = redfish
enabled_management_interfaces = redfish
enabled_inspect_interfaces = agent,redfish
default_network_interface = noop
default_boot_interface = redfish-virtual-media

[conductor]
deploy_kernel = file:///etc/kolla/config/ironic/ironic-agent.kernel
deploy_ramdisk =  file:///etc/kolla/config/ironic/ironic-agent.initramfs
bootloader = file:///var/lib/ironic/httpboot/esp.img

[neutron]
cleaning_network = none
